# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v2
        with:
          ref: release

      - uses: actions/setup-node@v2
      - uses: coturiv/setup-ionic@v1

      - name: Install node Packages
        run : npm i

      - name: Get code changes for build
        run: |
          git fetch
          git checkout master
          git checkout release
          git merge master --no-commit --squash

      - name: Build
        run: ionic build --prod

      - name: Initialise Commit
        run: | 
          git config user.email "simon@ineedsurgery.com"
          git config user.name "simon"
          git commit -m "Build"
      
      - name: Push Build
        run: git push
